### ISSUE TITLE
Car turns one direction regardless of the negative sign.

### ISSUE THREAD

**Issue by Fireflaker** [zerokol/Continuous2Wheels#1]
/*
   UNIVERSIDADE ESTADUAL DO PIAUÍ - UESPI
   Bac. em Ciências da Computação - CTU

   AJ Alves.

   aj.alves@live.com;
   aj.zerokol@gmail.com;

   zerokol.com
 */

/********************************************************************
 * EXAMPLE
 ********************************************************************/
 
#include <Servo.h>
#include <Continuous2Wheels.h> //Importing our Library

Servo rightWheel, leftWheel;
int rightWheelPin = 11; //Pin for right wheel
int leftWheelPin = 10; //Pin for left wheel
double wheelRadius = 3.3; //Radius for wheels in centimeters
double bendRadius = 10.7; //Bend radius is the distance for one wheel to another, it is the shaft length, in centimeters
double resistance = 2.6; //a estimated resistance for the middle in the wheels
// Creating a instance for our lib and setting the constructor
// Don't forget to pass a POINTER for right and left Servo objects
Continuous2Wheels c2w(&rightWheel, &leftWheel, wheelRadius, bendRadius, resistance);

void setup(){
  rightWheel.attach(rightWheelPin);
  leftWheel.attach(leftWheelPin);
  c2w.setBendSmooth(0.2); //Applying a smooth to bends
     Serial.begin(115200);
}

void loop(){
//  c2w.forward(45);
//  delay(4000);
//  c2w.backward(45);
//  delay(4000);
  c2w.bend(-90); // Make a left bent with 90°
  delay(4000);
  Serial.println("left");
  c2w.bend(90); // Make a right bent with 90°
  delay(4000);
  Serial.println("right");
//  c2w.bend(-90); // Make a left bent with 90°
//  delay(4000);
//  c2w.bend(-90); // Make a left bent with 90°
//  delay(4000);
//  c2w.spin(360); // Spin the robot 360° in its center, PS:. obstrusive, the robot stop in the end
//  c2w.forward(45);
//  delay(4000);
//  c2w.stop();
//  delay(10000);
}

Thank you for providing the library. I have an issue with the code provided. When turning, the robot turns only in one direction regardless of the negative sign. It does work perfectly with moving back and forth, though.

**Comment by alvesoaj** [comment]
Hello, it is weird! In any other test, did you make it works?

**Comment by Fireflaker** [comment]
Hi, Thanks for your attention.
The output waveforms seem fine and I guess it is my servos acting weird. I am now using WriteMilicesonconds function in the built-in servo library instead,
